### ISSUE TITLE
Building libraries with `clj-nix`

### ISSUE THREAD

**Issue by neshtea** [jlesquembre/clj-nix#3]
I just gave `clj-nix` a try and wanted to build an internal library using the flake. It is supposed to distributed as a `jar` (as most libraries are). 

I'm wondering if this is already possible with `clj-nix`.

- `mkCljBin` seems to be inteded for runnable applications (hence the required `main-ns` attribute.
- `customJdk` seems to be overkill. Or am I wrong here?

It is also very much possible that I misunderstood the documentation and there is an obvious answer.

**Comment by jlesquembre** [comment]
Thanks for giving it a try :)

Good points, I'd try to make that more clear in the documentation. Answering your questions:

- `mkCljBin`: you are right, it's intended for runnable applications. However, it's generating a jar in a different output (by output I mean a nix output path). You can run `nix build .#clj-tuto.lib`, the jar would be in the `result-lib`. You still have to provide a `main-ns` to the function, but just pass any string, I think in that case it doesn't matter. I didn't think about that use case, but maybe I should support it, especially since it seems quite easy to do. 
- `customJdk`: The intended use case is to generate a minimal JDK, which only makes sense if you want to deploy your application as a docker container (or maybe to generate a minimal VM) For a lib, or for a binary you want to run on your computer doesn't make any sense.

I hope that clarifies it a bit, I'd anyways try to improve the readme

**Comment by neshtea** [comment]
This answers my question, thank you.  I will give it a try

> You still have to provide a main-ns to the function, but just pass any string ... maybe I should support it, especially since it seems quite easy to do.

Yeah, I think it would be great if there was a `mkCljLib` or something similar.

**Comment by jlesquembre** [comment]
I added a `mkCljLib` function. You can see an example here:

https://github.com/jlesquembre/clj-demo-project/blob/fce3b5f23bdfb62f115e4f36241eb84f9f03c7f0/flake.nix#L38-L43

```nix
clj-lib = cljpkgs.mkCljLib {
  projectSrc = ./.;
  name = "me.lafuente/clj-tuto";
  version = "1.0";
  # buildCommand = "clj -T:build jar";
};
```
